### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by warwickgrace** [kakearney/boxplot2-pkg#2]
Hello Kelly
I appreciate your Matlab contributions. As usual this one is good too. 
I like boxplots for for presentation displays and like to modify the the image a lot. So your contribution is exactly good for that. And i guess that's why you created for yourself.

I dislike most boxplots because the whiskers use the 1.5 IQR rule. (And I know this is due to one if the statistics gurus). Much of my data is limited to positive values and skewed , eg wind speeds. So on the low side,  I.5*IQR or even  a standard deviation gives negative values this rule. 

Can you, without  great effort, include an input specification for the 10th and 90th percentile values instead of median plus or minus 1.5*IQR?
thanks
Warwick

**Comment by AmeerDotHydro** [comment]
Hello Kelly/warwickgrace,
How would one increase the whiskers range to include more outliers? I would like to increase the distance to 2 or even 3 instead of the default 1.5*IQR. Tried something like 
`set([h.lwhis h.uwhis], 'whisker',2);` but didn't work.

**Comment by kakearney** [comment]
This function is basically a wrapper around boxplot, so modifying the algorithm for calculating whisker length would require rewriting the box-generating code from scratch.  Sorry, that's beyond the scope of this little project.

However, the IQR-defined whiskers length should never exceed that of the data itself.  (Errorbars based on mean and standard deviation, on the other hand, may well exceed the data limits if you have highly skewed data).  The *maximum* whisker value is defined by Q1-W*(Q3-Q1) and Q3+W*(Q3-Q1), but those values are clipped to the most extreme adjacent value in the dataset itself.

In this function, you can change the whisker factor (W) from 1.5 to any value you want via the `whisker` input parameter, using the same syntax as in the original `boxplot` function.  (Note that this has to be done when the boxplots are created, and cannot be adjusted afterward).

```matlab
M = 1;
V = 5;

x = 1;

npt = 1000;
nx = length(x);

y = cat(2, ...
    random('norm', M, sqrt(V), npt,1), ...
    random('logn', log(M^2 / sqrt(V+M^2)), sqrt(log(V/M^2 + 1)), npt,1), ...
    random('exp', M, npt,1));

subplot(3,1,1);
hold on;
nhist(num2cell(y,1));
legend('1: normal', '2: lognormal', '3: exponential');
title('Histograms, with mean and standard deviation errorbars');

subplot(3,1,2);
boxplot2(y);
title('whisker = 1.5');

subplot(3,1,3);
boxplot2(y,'whisker', 10000);
title('whisker = 10000');
```

![boxtemp](https://user-images.githubusercontent.com/5015092/34788831-a3da1ad8-f5f0-11e7-8d4a-64fa29985776.png)
